package com.nova.engine;

import android.content.Context;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.*;
import java.util.*;

final class ProjectStore {
    static final String PROJECT_FILE="Nscript.project";
    private ProjectStore(){}
    static File root(Context c){File base=c.getExternalFilesDir(null);if(base==null)base=c.getFilesDir();File dir=new File(base,"projects");if(!dir.exists())dir.mkdirs();return dir;}
    static List<File> list(Context c){File[] fs=root(c).listFiles();ArrayList<File> out=new ArrayList<>();if(fs!=null)for(File f:fs)if(f.isDirectory()&&new File(f,PROJECT_FILE).isFile())out.add(f);Collections.sort(out,(a,b)->Long.compare(b.lastModified(),a.lastModified()));return out;}
    static File create(Context c,String name,int minSdk,int targetSdk,String abi,String template,String orientation)throws Exception{
        if(!name.matches("[\\p{L}\\p{N}_-]{1,40}"))throw new Exception("Используй до 40 букв, цифр, дефисов или _.");
        File dir=new File(root(c),name);if(dir.exists())throw new Exception("Проект с таким именем уже есть.");
        String[] folders={"scripts","assets/models","assets/textures","assets/sprites","assets/audio","native/include","native/src","docs"};
        for(String f:folders)if(!new File(dir,f).mkdirs()&&!new File(dir,f).isDirectory())throw new IOException("Не удалось создать папку "+f);
        JSONObject project=new JSONObject();project.put("format",1);project.put("projectName",name);project.put("engineVersion","0.04");project.put("apiVersion","0.1");project.put("template",template);
        JSONObject android=new JSONObject();android.put("minSdk",minSdk);android.put("targetSdk",targetSdk);android.put("orientation",orientation);android.put("package",packageName(name));android.put("abi",abi);project.put("android",android);
        JSONObject build=new JSONObject();build.put("output",name+".apk");project.put("build",build);JSONObject ai=new JSONObject();ai.put("providers",new JSONArray());ai.put("active",0);project.put("ai",ai);
        write(new File(dir,PROJECT_FILE),project.toString(2));
        JSONObject scene=new JSONObject();scene.put("format",1);JSONArray objects=new JSONArray();
        if("3d".equals(template)){objects.put(obj("Camera","camera",0,3,8));objects.put(obj("Sun","light",3,6,2));objects.put(obj("Ground","plane",0,0,0));objects.put(obj("Cube","cube",0,0.5,0));}
        else if("2d".equals(template)){objects.put(obj("Camera","camera",0,0,10));objects.put(obj("Player","cube",0,0,0));}
        else if("ui".equals(template)||"app".equals(template)){objects.put(obj("Camera","camera",0,0,10));}
        scene.put("objects",objects);write(new File(dir,"scene.nscn"),scene.toString(2));
        String script="class Main : Script {\n    void OnStart() {\n        Log.Print(\"Nova ready\");\n    }\n\n    void OnUpdate(float dt) {\n        // Your game logic\n    }\n}\n";
        write(new File(dir,"scripts/Main.ns"),script);
        write(new File(dir,"docs/NovaScript.md"),"NovaScript project. See runtime subset in project documentation.\n");
        writeNativeTemplate(dir);
        return dir;
    }
    private static void writeNativeTemplate(File project)throws IOException{
        write(new File(project,"native/include/NovaNative.h"),"#pragma once\n#include <cstdint>\n\n#if defined(__GNUC__)\n#define NOVA_EXPORT __attribute__((visibility(\"default\")))\n#else\n#define NOVA_EXPORT\n#endif\n\nextern \"C\" {\nstruct NovaApiV1 {\n    std::uint32_t abiVersion;\n    void (*log)(int level, const char* message);\n    bool (*getNumber)(void* object, const char* key, double* outValue);\n    void (*setNumber)(void* object, const char* key, double value);\n};\nstruct NovaObjectApiV1 { void* userData; };\n// The host maps the rotationY property to the named scene object and renders it.\nstruct NovaFrameV1 { float deltaTime; double elapsedTime; std::uint64_t frame; };\nstruct NovaComponentV1 {\n    std::uint32_t abiVersion;\n    void* state;\n    void (*onStart)(void* state, const NovaApiV1* api, NovaObjectApiV1* object);\n    void (*onUpdate)(void* state, const NovaApiV1* api, NovaObjectApiV1* object, const NovaFrameV1* frame);\n    void (*onDestroy)(void* state, const NovaApiV1* api, NovaObjectApiV1* object);\n};\nNOVA_EXPORT std::uint32_t Nova_GetAbiVersion();\nNOVA_EXPORT bool Nova_CreateComponent(NovaComponentV1* outComponent);\n}\n");
        write(new File(project,"native/src/NovaComponent.cpp"),"#include \"NovaNative.h\"\n#include <new>\n\nnamespace {\nstruct SpinState { double degreesPerSecond = 45.0; double angle = 0.0; };\nvoid onStart(void* raw, const NovaApiV1* api, NovaObjectApiV1* object) {\n    if (!raw) return;\n    auto* state = static_cast<SpinState*>(raw);\n    if (api && api->log) api->log(0, \"Nova C++ component started\");\n    double speed = 0.0;\n    if (api && api->getNumber && object && api->getNumber(object->userData, \"degreesPerSecond\", &speed))\n        state->degreesPerSecond = speed;\n}\nvoid onUpdate(void* raw, const NovaApiV1* api, NovaObjectApiV1* object, const NovaFrameV1* frame) {\n    if (!raw || !frame) return;\n    auto* state = static_cast<SpinState*>(raw);\n    state->angle += state->degreesPerSecond * frame->deltaTime;\n    if (api && api->setNumber && object)\n        api->setNumber(object->userData, \"rotationY\", state->angle);\n}\nvoid onDestroy(void* raw, const NovaApiV1*, NovaObjectApiV1*) {\n    delete static_cast<SpinState*>(raw);\n}\n}\n\nextern \"C\" NOVA_EXPORT std::uint32_t Nova_GetAbiVersion() { return 1; }\nextern \"C\" NOVA_EXPORT bool Nova_CreateComponent(NovaComponentV1* out) {\n    if (!out) return false;\n    auto* state = new (std::nothrow) SpinState();\n    if (!state) return false;\n    out->abiVersion = 1;\n    out->state = state;\n    out->onStart = onStart;\n    out->onUpdate = onUpdate;\n    out->onDestroy = onDestroy;\n    return true;\n}\n");
        write(new File(project,"native/src/NovaJniBridge.cpp"),"#include \"NovaNative.h\"\n#include <jni.h>\n#include <new>\n#include <string>\n#include <cstring>\n\nnamespace {\nstruct NativeHandle {\n    NovaComponentV1 component{};\n    NovaApiV1 api{};\n    NovaObjectApiV1 object{};\n    double rotationY = 0.0;\n    double degreesPerSecond = 45.0;\n    char targetName[256]{};\n};\nvoid logMessage(int, const char*) {}\nbool getNumber(void* raw, const char* key, double* out) {\n    if (!raw || !key || !out) return false;\n    auto* h = static_cast<NativeHandle*>(raw);\n    if (std::string(key) == \"rotationY\") { *out = h->rotationY; return true; }\n    if (std::string(key) == \"degreesPerSecond\") { *out = h->degreesPerSecond; return true; }\n    return false;\n}\nvoid setNumber(void* raw, const char* key, double value) {\n    if (!raw || !key) return;\n    auto* h = static_cast<NativeHandle*>(raw);\n    if (std::string(key) == \"rotationY\") h->rotationY = value;\n    else if (std::string(key) == \"degreesPerSecond\") h->degreesPerSecond = value;\n}\nNativeHandle* from(jlong value) { return reinterpret_cast<NativeHandle*>(static_cast<std::uintptr_t>(value)); }\n}\n\nextern \"C\" JNIEXPORT jlong JNICALL\nJava_com_nova_engine_NativeComponent_nativeCreate(JNIEnv* env, jclass, jstring targetName) {\n    auto* h = new (std::nothrow) NativeHandle();\n    if (!h) return 0;\n    h->api = {1, logMessage, getNumber, setNumber};\n    h->object.userData = h;\n    if (targetName) { const char* chars = env->GetStringUTFChars(targetName, nullptr); if (chars) { std::strncpy(h->targetName, chars, sizeof(h->targetName)-1); env->ReleaseStringUTFChars(targetName, chars); } }\n    if (Nova_GetAbiVersion() != 1 || !Nova_CreateComponent(&h->component) || h->component.abiVersion != 1) {\n        delete h;\n        return 0;\n    }\n    if (h->component.onStart) h->component.onStart(h->component.state, &h->api, &h->object);\n    return static_cast<jlong>(reinterpret_cast<std::uintptr_t>(h));\n}\nextern \"C\" JNIEXPORT jdouble JNICALL\nJava_com_nova_engine_NativeComponent_nativeUpdate(JNIEnv*, jclass, jlong value, jfloat dt, jdouble elapsed, jlong frame) {\n    NativeHandle* h = from(value);\n    if (!h) return 0.0;\n    if (h->component.onUpdate) { NovaFrameV1 f{dt, elapsed, static_cast<std::uint64_t>(frame)}; h->component.onUpdate(h->component.state, &h->api, &h->object, &f); }\n    return static_cast<jdouble>(h->rotationY);\n}\nextern \"C\" JNIEXPORT void JNICALL\nJava_com_nova_engine_NativeComponent_nativeDestroy(JNIEnv*, jclass, jlong value) {\n    NativeHandle* h = from(value);\n    if (!h) return;\n    if (h->component.onDestroy) h->component.onDestroy(h->component.state, &h->api, &h->object);\n    delete h;\n}\n");
        write(new File(project,"native/CMakeLists.txt"),"cmake_minimum_required(VERSION 3.18)\nproject(NovaNativeComponent LANGUAGES CXX)\nadd_library(NovaComponent SHARED src/NovaComponent.cpp src/NovaJniBridge.cpp)\ntarget_include_directories(NovaComponent PRIVATE include)\ntarget_compile_features(NovaComponent PRIVATE cxx_std_17)\ntarget_compile_options(NovaComponent PRIVATE -Wall -Wextra -fvisibility=hidden)\nset_target_properties(NovaComponent PROPERTIES OUTPUT_NAME \"NovaComponent\")\n");
        write(new File(project,"native/README.md"),"# Nova C++ NDK component template\n\nVersioned C ABI plugin plus JNI bridge used by `NativeComponent.java`. Build with Android NDK CMake:\n\n```sh\nexport ANDROID_NDK_HOME=/path/to/android-ndk\ncmake -S . -B build \\\n  -DCMAKE_TOOLCHAIN_FILE=\"$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake\" \\\n  -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-24 \\\n  -DCMAKE_BUILD_TYPE=Release\ncmake --build build\n```\n\nCopy `libNovaComponent.so` into `native/arm64-v8a/`. For 32-bit devices build with `-DANDROID_ABI=armeabi-v7a` and use `native/armeabi-v7a/`. In the editor open the folder menu, choose `.so`, and select the library. The loader copies it to the current ABI folder, calls `System.load`, verifies ABI version 1, creates the component, ticks `onUpdate` while the editor remains open, and calls `onDestroy` when leaving.\n\nExports: `Nova_GetAbiVersion()` and `Nova_CreateComponent()`. `NovaJniBridge.cpp` exposes JNI lifecycle methods for `com.nova.engine.NativeComponent`.\n\n**Current limit:** lifecycle loading works, but sample numeric properties are not yet mapped to visible scene transforms. Verify Android ABI, JNI export names, and NDK build if loading fails.\n");
    }
    private static JSONObject obj(String name,String type,double x,double y,double z)throws Exception{JSONObject o=new JSONObject();o.put("name",name);o.put("type",type);JSONArray p=new JSONArray();p.put(x);p.put(y);p.put(z);o.put("position",p);return o;}
    private static String packageName(String n){StringBuilder b=new StringBuilder();for(char ch:n.toLowerCase(Locale.US).toCharArray())if((ch>='a'&&ch<='z')||(ch>='0'&&ch<='9'))b.append(ch);if(b.length()==0||Character.isDigit(b.charAt(0)))b.insert(0,"game");return "com.nova.games."+b;}
    static JSONObject readProject(File dir){try{return new JSONObject(read(new File(dir,PROJECT_FILE)));}catch(Exception e){return new JSONObject();}}
    static String read(File f)throws IOException{ByteArrayOutputStream b=new ByteArrayOutputStream();try(InputStream in=new FileInputStream(f)){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)b.write(buf,0,n);}return new String(b.toByteArray(),"UTF-8");}
    static void write(File f,String value)throws IOException{File p=f.getParentFile();if(p!=null&&!p.exists())p.mkdirs();try(OutputStream o=new FileOutputStream(f)){o.write(value.getBytes("UTF-8"));}}
}
