package com.nova.engine;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.app.Dialog;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.InputType;
import android.text.TextUtils;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.*;

public class WorkspaceActivity extends Activity {
    private final Handler ui=new Handler(Looper.getMainLooper());
    private final ArrayList<JSONObject> history=new ArrayList<>();
    private File dir,sceneFile; private JSONObject project; private SceneView sceneView; private NovaScriptRuntime runtime; private static final int PICK_MODEL=4102, PICK_NATIVE=4104; private final ArrayList<NativeComponent> nativeComponents=new ArrayList<>(); private long nativeLastNs=0,nativeFrame=0; private final Runnable nativeTick=new Runnable(){public void run(){if(isFinishing()||nativeComponents.isEmpty())return;long now=System.nanoTime();float dt=nativeLastNs==0?.016f:Math.min(.1f,(now-nativeLastNs)/1_000_000_000f);nativeLastNs=now;for(NativeComponent c:new ArrayList<>(nativeComponents))try{double angle=c.update(dt,now/1_000_000_000.0,nativeFrame);if(sceneView!=null)sceneView.setNativeRotation(c.targetName(),angle);}catch(Throwable e){log("Native component error: "+e.getMessage(),0xFFFF7C86);}nativeFrame++;ui.postDelayed(this,16);}};
    private LinearLayout chatMessages,files,log; private ScrollView chatScroll,logScroll; private EditText prompt; private IconButton send,providerButton,runButton,folderButton,logsButton; private LinearLayout consolePanel; private boolean busy,logsVisible=true;
    @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);String p=getIntent().getStringExtra("project");if(p==null){finish();return;}dir=new File(p);sceneFile=new File(dir,"scene.nscn");project=ProjectStore.readProject(dir);build();refreshFiles();log("Открыт проект "+dir.getName(),Ui.GREEN);if(provider()==null)addMessage("Сначала подключи провайдера через кнопку «ИИ-провайдер».",false);else addMessage("Опиши, что изменить в сцене. Например: создай красный куб и поставь его над землёй.",false);}
    @Override protected void onResume(){super.onResume();if(sceneView!=null)sceneView.onResume();if(!nativeComponents.isEmpty()){nativeLastNs=0;ui.removeCallbacks(nativeTick);ui.post(nativeTick);}}
    @Override protected void onPause(){ui.removeCallbacks(nativeTick);persistNativeRotations();for(NativeComponent c:new ArrayList<>(nativeComponents))c.close();nativeComponents.clear();if(runtime!=null&&runtime.isRunning()){runtime.stop();if(runButton!=null)runButton.setIcon(IconButton.PLAY);}if(sceneView!=null)sceneView.onPause();super.onPause();}
    private void build(){
        int gap=Ui.dp(this,8), pad=Ui.dp(this,10);
        LinearLayout root=Ui.col(this);root.setBackgroundColor(Ui.BG);
        LinearLayout body=Ui.row(this);body.setPadding(pad,pad,pad,pad);root.addView(body,new LinearLayout.LayoutParams(Ui.MATCH,0,1));

        LinearLayout left=panel();
        LinearLayout chatHead=Ui.row(this);
        providerButton=new IconButton(this,IconButton.PLUS,"Добавить ИИ-провайдера");
        providerButton.setOnClickListener(v->providerDialog(true));chatHead.addView(providerButton);
        TextView chatTitle=Ui.text(this,"ИИ",13,Ui.MUTED,true);chatTitle.setPadding(Ui.dp(this,8),0,0,0);chatHead.addView(chatTitle);
        left.addView(chatHead);
        chatScroll=new ScrollView(this);chatMessages=Ui.col(this);chatMessages.setPadding(0,Ui.dp(this,8),0,Ui.dp(this,8));chatScroll.addView(chatMessages);
        left.addView(chatScroll,new LinearLayout.LayoutParams(Ui.MATCH,0,1));
        LinearLayout inputRow=Ui.row(this);inputRow.setPadding(Ui.dp(this,5),Ui.dp(this,3),Ui.dp(this,4),Ui.dp(this,3));inputRow.setBackground(Ui.shape(this,Ui.RAISED,28,Ui.EDGE));
        prompt=Ui.input(this,"Напиши запрос…");prompt.setSingleLine(false);prompt.setMinLines(1);prompt.setMaxLines(3);prompt.setBackgroundColor(android.graphics.Color.TRANSPARENT);prompt.setPadding(Ui.dp(this,11),Ui.dp(this,7),Ui.dp(this,6),Ui.dp(this,7));prompt.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);inputRow.addView(prompt,new LinearLayout.LayoutParams(0,Ui.WRAP,1));
        send=new IconButton(this,IconButton.SEND,"Отправить");send.setOnClickListener(v->sendPrompt());inputRow.addView(send);left.addView(inputRow);
        body.addView(left,new LinearLayout.LayoutParams(0,Ui.MATCH,2.5f));

        LinearLayout center=Ui.col(this);center.setPadding(gap,0,gap,0);
        sceneView=new SceneView(this,new SceneView.FileScene(sceneFile));sceneView.setOnObjectTapListener(this::editObject);sceneView.setOnObjectDragListener(this::dragObject);
        FrameLayout frame=new FrameLayout(this);frame.setBackground(Ui.shape(this,Ui.PANEL,13,Ui.EDGE));frame.addView(sceneView);
        LinearLayout controls=Ui.row(this);controls.setPadding(Ui.dp(this,6),Ui.dp(this,6),Ui.dp(this,6),Ui.dp(this,6));controls.setBackground(Ui.shape(this,0xCC1D1D22,12,0));
        Button objectsButton=Ui.button(this,"Объекты",false);objectsButton.setOnClickListener(v->showObjectPicker());controls.addView(objectsButton);
        folderButton=new IconButton(this,IconButton.FOLDER,"Открыть файлы проекта");folderButton.setOnClickListener(v->showProjectFiles());controls.addView(folderButton);
        runButton=new IconButton(this,IconButton.PLAY,"Запустить NovaScript");runButton.setOnClickListener(v->toggleRuntime());controls.addView(runButton);
        logsButton=new IconButton(this,IconButton.LOGS,"Скрыть консоль");logsButton.setOnClickListener(v->toggleLogs());controls.addView(logsButton);
        FrameLayout.LayoutParams controlsLp=new FrameLayout.LayoutParams(Ui.WRAP,Ui.WRAP,Gravity.TOP|Gravity.RIGHT);controlsLp.setMargins(0,Ui.dp(this,8),Ui.dp(this,8),0);frame.addView(controls,controlsLp);
        center.addView(frame,new LinearLayout.LayoutParams(Ui.MATCH,0,6));

        consolePanel=panel();LinearLayout conHead=Ui.row(this);conHead.addView(Ui.text(this,"КОНСОЛЬ",10,Ui.MUTED,true),new LinearLayout.LayoutParams(0,Ui.WRAP,1));IconButton clear=new IconButton(this,IconButton.CLEAR,"Очистить консоль");clear.setOnClickListener(v->log.removeAllViews());conHead.addView(clear);consolePanel.addView(conHead);
        logScroll=new ScrollView(this);log=Ui.col(this);logScroll.addView(log);consolePanel.addView(logScroll,new LinearLayout.LayoutParams(Ui.MATCH,0,1));LinearLayout.LayoutParams consoleLp=new LinearLayout.LayoutParams(Ui.MATCH,0,2.5f);consoleLp.topMargin=gap;center.addView(consolePanel,consoleLp);
        body.addView(center,new LinearLayout.LayoutParams(0,Ui.MATCH,5.5f));
        setContentView(root);updateProviderLabel();
        runtime=new NovaScriptRuntime(dir,new NovaScriptRuntime.Logger(){public void line(String text,boolean error){runOnUiThread(()->log(text,error?0xFFFF7C86:Ui.TEXT));}public void changed(){runOnUiThread(()->{if(sceneView!=null)sceneView.reload();});}});
    }
    private void toggleLogs(){logsVisible=!logsVisible;consolePanel.setVisibility(logsVisible?View.VISIBLE:View.GONE);logsButton.setContentDescription(logsVisible?"Скрыть консоль":"Показать консоль");}
    private void showProjectFiles(){
        Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);
        LinearLayout box=Ui.col(this);box.setPadding(Ui.dp(this,16),Ui.dp(this,14),Ui.dp(this,16),Ui.dp(this,14));box.setBackground(Ui.shape(this,Ui.PANEL,18,Ui.EDGE));
        LinearLayout head=Ui.row(this);head.addView(Ui.text(this,"Файлы проекта",18,Ui.TEXT,true),new LinearLayout.LayoutParams(0,Ui.WRAP,1));IconButton close=new IconButton(this,IconButton.CLOSE,"Закрыть");head.addView(close);box.addView(head);
        ScrollView scroll=new ScrollView(this);LinearLayout entries=Ui.col(this);entries.setPadding(0,Ui.dp(this,8),0,0);scroll.addView(entries);box.addView(scroll,new LinearLayout.LayoutParams(Ui.MATCH,0,1));
        LinearLayout actions=Ui.row(this);IconButton addObj=new IconButton(this,IconButton.MODEL,"Импортировать 3D-модель");addObj.setOnClickListener(v->{d.dismiss();pickModel();});actions.addView(addObj);TextView tip=Ui.text(this,"3D модель",10,Ui.MUTED,false);tip.setPadding(Ui.dp(this,5),0,Ui.dp(this,12),0);actions.addView(tip);IconButton addNative=new IconButton(this,IconButton.OPEN,"Загрузить нативную библиотеку .so");addNative.setOnClickListener(v->{d.dismiss();pickNative();});actions.addView(addNative);TextView nt=Ui.text(this,".so",10,Ui.MUTED,false);nt.setPadding(Ui.dp(this,5),0,0,0);actions.addView(nt);box.addView(actions);
        addProjectEntries(dir,entries,0,d);
        d.setContentView(box);d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.show();int w=Math.min((int)(getResources().getDisplayMetrics().widthPixels*.78f),Ui.dp(this,720));int h=Math.min((int)(getResources().getDisplayMetrics().heightPixels*.84f),Ui.dp(this,680));d.getWindow().setLayout(w,h);close.setOnClickListener(v->d.dismiss());
    }
    private boolean isOpenableText(File f){String n=f.getName().toLowerCase(Locale.US);return n.endsWith(".ns")||n.endsWith(".java")||n.endsWith(".cpp")||n.endsWith(".h")||n.endsWith(".hpp")||n.endsWith(".md")||n.endsWith(".txt")||n.endsWith(".json")||n.endsWith(".xml")||n.endsWith(".gradle")||n.equals("cmakelists.txt");}
    private void addProjectEntries(File folder,LinearLayout target,int depth,Dialog dialog){File[] list=folder.listFiles();if(list==null)return;Arrays.sort(list,(a,b)->a.isDirectory()!=b.isDirectory()?(a.isDirectory()?-1:1):a.getName().compareToIgnoreCase(b.getName()));for(File f:list){if(f.getName().startsWith("."))continue;if(!f.isDirectory()&&!isOpenableText(f))continue;LinearLayout row=Ui.row(this);row.setPadding(Ui.dp(this,depth*14+7),Ui.dp(this,5),Ui.dp(this,6),Ui.dp(this,5));TextView label=Ui.text(this,(f.isDirectory()?"▸   ":"   ")+f.getName(),13,f.isDirectory()?Ui.MUTED:Ui.TEXT,f.isDirectory());row.addView(label,new LinearLayout.LayoutParams(0,Ui.WRAP,1));if(!f.isDirectory()){IconButton open=new IconButton(this,IconButton.OPEN,"Открыть "+f.getName());row.addView(open);open.setOnClickListener(v->{dialog.dismiss();openCodeFile(f);});row.setOnClickListener(v->{dialog.dismiss();openCodeFile(f);});}target.addView(row);if(f.isDirectory())addProjectEntries(f,target,depth+1,dialog);}}
    private void openCodeFile(File file){Intent i=new Intent(this,CodeEditorActivity.class);i.putExtra("path",file.getAbsolutePath());i.putExtra("project",dir.getAbsolutePath());startActivityForResult(i,4103);}
    private void pickNative(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/octet-stream");startActivityForResult(i,PICK_NATIVE);}
    private void pickModel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"model/obj","model/gltf+json","model/gltf-binary","application/octet-stream","text/plain"});startActivityForResult(i,PICK_MODEL);}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==4103){refreshFiles();return;}if(resultCode!=RESULT_OK||data==null||data.getData()==null)return;if(requestCode==PICK_NATIVE){importNative(data.getData());return;}if(requestCode!=PICK_MODEL)return;Uri uri=data.getData();String display="model.obj";android.database.Cursor cursor=getContentResolver().query(uri,null,null,null,null);if(cursor!=null){try{int col=cursor.getColumnIndex(android.provider.OpenableColumns.DISPLAY_NAME);if(cursor.moveToFirst()&&col>=0)display=cursor.getString(col);}finally{cursor.close();}}String ext=display.toLowerCase(Locale.US);if(!ext.endsWith(".obj")&&!ext.endsWith(".gltf")&&!ext.endsWith(".glb")){toast("Выбери файл OBJ, glTF или GLB.");return;}try{File folder=new File(dir,"assets/models");if(!folder.exists())folder.mkdirs();File dest=new File(folder,display.replaceAll("[^A-Za-z0-9._-]","_"));try(java.io.InputStream in=getContentResolver().openInputStream(uri);java.io.OutputStream out=new java.io.FileOutputStream(dest)){if(in==null)throw new Exception("Не удалось открыть файл");byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);}JSONObject root=new JSONObject(ProjectStore.read(sceneFile));JSONArray arr=root.optJSONArray("objects");if(arr==null){arr=new JSONArray();root.put("objects",arr);}JSONObject object=new JSONObject();String base=dest.getName();int dot=base.lastIndexOf('.');if(dot>0)base=base.substring(0,dot);object.put("name",uniqueObjectName(arr,base));object.put("type","model");object.put("modelPath","assets/models/"+dest.getName());object.put("visible",true);object.put("position",new JSONArray().put(0).put(0).put(0));object.put("rotation",new JSONArray().put(0).put(0).put(0));object.put("scale",new JSONArray().put(1).put(1).put(1));object.put("color",new JSONArray().put(.78).put(.8).put(.86));arr.put(object);ProjectStore.write(sceneFile,root.toString(2));sceneView.reload();refreshFiles();log("Модель импортирована: "+dest.getName(),Ui.GREEN);}catch(Exception e){toast("Импорт модели: "+e.getMessage());log("Импорт модели: "+e.getMessage(),0xFFFF7C86);}}
    private String firstRenderableName(){try{JSONObject root=new JSONObject(ProjectStore.read(sceneFile));JSONArray a=root.optJSONArray("objects");for(int i=0;a!=null&&i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&o.optBoolean("visible",true)&&!"camera".equals(o.optString("type"))&&!"light".equals(o.optString("type")))return o.optString("name");}}catch(Exception ignored){}return null;}
    private void persistNativeRotations(){try{JSONObject root=new JSONObject(ProjectStore.read(sceneFile));JSONArray a=root.optJSONArray("objects");if(a==null)return;for(NativeComponent c:nativeComponents){for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&c.targetName().equals(o.optString("name"))){JSONArray r=o.optJSONArray("rotation");if(r==null)r=new JSONArray().put(0).put(0).put(0);r.put(1,c.rotationY());o.put("rotation",r);}}}ProjectStore.write(sceneFile,root.toString(2));}catch(Exception e){log("Не удалось сохранить native rotation: "+e.getMessage(),0xFFFF7C86);}}
    private void importNative(Uri uri){String display="libNovaComponent.so";android.database.Cursor cursor=getContentResolver().query(uri,null,null,null,null);if(cursor!=null){try{int col=cursor.getColumnIndex(android.provider.OpenableColumns.DISPLAY_NAME);if(cursor.moveToFirst()&&col>=0)display=cursor.getString(col);}finally{cursor.close();}}if(!display.endsWith(".so")){toast("Выбери файл с расширением .so");return;}try{String abi=android.os.Build.SUPPORTED_ABIS.length>0?android.os.Build.SUPPORTED_ABIS[0]:"armeabi-v7a";File folder=new File(new File(dir,"native"),abi);if(!folder.exists())folder.mkdirs();File dest=new File(folder,display.replaceAll("[^A-Za-z0-9_.-]","_"));try(java.io.InputStream in=getContentResolver().openInputStream(uri);java.io.OutputStream out=new java.io.FileOutputStream(dest)){if(in==null)throw new Exception("Файл не прочитан");byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);}String base=dest.getName();if(base.startsWith("lib"))base=base.substring(3);if(base.endsWith(".so"))base=base.substring(0,base.length()-3);String target=firstRenderableName();if(target==null)throw new Exception("В сцене нет объекта для вращения");NativeComponent component=NativeLibraryManager.load(this,dir,base,target);nativeComponents.add(component);nativeLastNs=0;ui.removeCallbacks(nativeTick);ui.post(nativeTick);refreshFiles();log("Загружен .so: "+dest.getName()+" ("+abi+")",Ui.GREEN);toast("Нативный компонент загружен. При выходе из редактора он остановится.");}catch(Throwable e){log("Ошибка загрузки .so: "+e.getMessage(),0xFFFF7C86);toast("Не удалось загрузить .so: "+e.getMessage());}}
    private String uniqueObjectName(JSONArray arr,String base)throws Exception{String name=base;int suffix=2;while(true){boolean found=false;for(int i=0;i<arr.length();i++)if(name.equals(arr.getJSONObject(i).optString("name"))){found=true;break;}if(!found)return name;name=base+" "+suffix++;}}
    private void toggleRuntime(){if(runtime==null)return;if(runtime.isRunning()){runtime.stop();runButton.setIcon(IconButton.PLAY);log("NovaScript остановлен",0xFFFFC857);}else{runtime.start();runButton.setIcon(IconButton.STOP);log("NovaScript запущен (подмножество v0.07)",Ui.GREEN);}}
    private void dragObject(String name,float dx,float dz,boolean finished){if(dx==0&&dz==0)return;try{JSONObject root=new JSONObject(ProjectStore.read(sceneFile));JSONArray a=root.optJSONArray("objects");for(int i=0;a!=null&&i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&name.equals(o.optString("name"))){JSONArray p=o.optJSONArray("position");if(p==null)p=new JSONArray().put(0).put(0).put(0);p.put(0,p.optDouble(0)+dx);p.put(2,p.optDouble(2)+dz);o.put("position",p);ProjectStore.write(sceneFile,root.toString(2));break;}}}catch(Exception e){log("Drag: "+e.getMessage(),0xFFFF7C86);}}
    private void showObjectPicker(){try{JSONObject root=new JSONObject(ProjectStore.read(sceneFile));JSONArray arr=root.optJSONArray("objects");LinearLayout box=Ui.col(this);box.setPadding(Ui.dp(this,18),Ui.dp(this,16),Ui.dp(this,18),Ui.dp(this,16));box.setBackground(Ui.shape(this,Ui.PANEL,18,Ui.EDGE));box.addView(Ui.text(this,"Объекты сцены",19,Ui.TEXT,true));EditText search=Ui.input(this,"Поиск по имени или типу");box.addView(search);ScrollView sc=new ScrollView(this);LinearLayout rows=Ui.col(this);sc.addView(rows);box.addView(sc,new LinearLayout.LayoutParams(Ui.MATCH,0,1));Runnable fill=()->{rows.removeAllViews();String q=search.getText().toString().trim().toLowerCase(Locale.US);for(int i=0;arr!=null&&i<arr.length();i++){JSONObject o=arr.optJSONObject(i);if(o==null)continue;String name=o.optString("name"),type=o.optString("type");if(!q.isEmpty()&&!name.toLowerCase(Locale.US).contains(q)&&!type.toLowerCase(Locale.US).contains(q))continue;Button b=Ui.button(this,name+"   ·   "+type,false);rows.addView(b,Ui.lp(Ui.MATCH,Ui.WRAP,0));b.setOnClickListener(v->{sceneView.selectObject(name);editObject(name);});}};fill.run();search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){fill.run();}public void afterTextChanged(android.text.Editable e){}});Button done=Ui.button(this,"Закрыть",true);box.addView(done,Ui.lp(Ui.MATCH,Ui.WRAP,0));Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);d.setContentView(box);d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.show();d.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.7f),(int)(getResources().getDisplayMetrics().heightPixels*.8f));done.setOnClickListener(v->d.dismiss());}catch(Exception e){toast("Не удалось прочитать объекты: "+e.getMessage());}}
    private void showObjects(){showObjectPicker();}
    private void editObject(String name){try{JSONObject root=new JSONObject(ProjectStore.read(sceneFile));JSONArray arr=root.optJSONArray("objects");JSONObject obj=null;int idx=-1;for(int i=0;arr!=null&&i<arr.length();i++)if(name.equals(arr.getJSONObject(i).optString("name"))){obj=arr.getJSONObject(i);idx=i;break;}if(obj==null)return;final int index=idx;LinearLayout box=Ui.col(this);box.setPadding(Ui.dp(this,18),Ui.dp(this,16),Ui.dp(this,18),Ui.dp(this,16));box.setBackground(Ui.shape(this,Ui.PANEL,18,Ui.EDGE));box.addView(Ui.text(this,"Свойства объекта",19,Ui.TEXT,true));EditText nm=Ui.input(this,"Имя");nm.setText(name);box.addView(nm);String[] keys={"position","rotation","scale","color"};EditText[] fields=new EditText[4];for(int k=0;k<keys.length;k++){box.addView(Ui.label(this,keys[k].toUpperCase(Locale.US)+" · x,y,z"));fields[k]=Ui.input(this,"0, 0, 0");JSONArray v=obj.optJSONArray(keys[k]);if(v!=null&&v.length()>=3)fields[k].setText(v.optDouble(0)+", "+v.optDouble(1)+", "+v.optDouble(2));box.addView(fields[k]);}LinearLayout actions=Ui.row(this);Button del=Ui.button(this,"Удалить",false);del.setTextColor(0xFFFF7C86);actions.addView(del);View sp=new View(this);actions.addView(sp,new LinearLayout.LayoutParams(0,1,1));Button save=Ui.button(this,"Сохранить",true);actions.addView(save);LinearLayout.LayoutParams ap=Ui.lp(Ui.MATCH,Ui.WRAP,0);ap.topMargin=Ui.dp(this,12);box.addView(actions,ap);Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);d.setContentView(box);d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.show();d.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.62f),WindowManager.LayoutParams.WRAP_CONTENT);save.setOnClickListener(v->{try{JSONObject fresh=new JSONObject(ProjectStore.read(sceneFile));JSONArray a=fresh.getJSONArray("objects");JSONObject target=a.getJSONObject(index);String newName=nm.getText().toString().trim();if(!newName.isEmpty())target.put("name",newName);for(int k=0;k<keys.length;k++){String[] parts=fields[k].getText().toString().trim().split("[, ]+");if(parts.length<3)throw new Exception(keys[k]+": введи 3 числа через запятую");JSONArray vec=new JSONArray();for(int q=0;q<3;q++)vec.put(Double.parseDouble(parts[q]));target.put(keys[k],vec);}ProjectStore.write(sceneFile,fresh.toString(2));sceneView.reload();refreshFiles();d.dismiss();log("Объект обновлён: "+newName,Ui.GREEN);}catch(Exception e){toast("Проверь свойства: "+e.getMessage());}});del.setOnClickListener(v->{try{JSONObject fresh=new JSONObject(ProjectStore.read(sceneFile));fresh.getJSONArray("objects").remove(index);ProjectStore.write(sceneFile,fresh.toString(2));sceneView.reload();d.dismiss();showObjects();log("Удалён объект "+name,0xFFFFC857);}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){toast("Не удалось открыть свойства: "+e.getMessage());}}
    private LinearLayout panel(){LinearLayout l=Ui.col(this);int p=Ui.dp(this,9);l.setPadding(p,p,p,p);l.setBackground(Ui.shape(this,Ui.PANEL,12,Ui.EDGE));return l;}
    private JSONArray providers(){JSONObject ai=project.optJSONObject("ai");if(ai==null){ai=new JSONObject();try{ai.put("providers",new JSONArray());ai.put("active",0);project.put("ai",ai);}catch(Exception ignored){}}JSONArray a=ai.optJSONArray("providers");if(a==null){a=new JSONArray();try{ai.put("providers",a);}catch(Exception ignored){}}return a;}
    private JSONObject provider(){JSONArray a=providers();if(a.length()==0)return null;int index=project.optJSONObject("ai").optInt("active",0);if(index<0||index>=a.length())index=0;return a.optJSONObject(index);}
    private void saveProject(){try{ProjectStore.write(new File(dir,ProjectStore.PROJECT_FILE),project.toString(2));}catch(Exception e){log("Не удалось сохранить настройки: "+e.getMessage(),0xFFFF7C86);}}
    private void updateProviderLabel(){JSONObject p=provider();providerButton.setContentDescription(p==null?"Добавить ИИ-провайдера":("Провайдер: "+p.optString("name","ИИ")));send.setEnabled(p!=null&&!busy);send.setAlpha(p!=null&&!busy?1f:.45f);}
    private void providerDialog(boolean addNew){JSONArray list=providers();JSONObject old=addNew?null:provider();LinearLayout box=Ui.col(this);box.setPadding(Ui.dp(this,18),Ui.dp(this,16),Ui.dp(this,18),Ui.dp(this,18));box.setBackground(Ui.shape(this,Ui.PANEL,20,Ui.EDGE));box.addView(Ui.text(this,addNew?"Добавить ИИ-провайдера":"Провайдер ИИ",20,Ui.TEXT,true));box.addView(Ui.label(this,"ИМЯ"));EditText name=Ui.input(this,"Например, OpenAI");box.addView(name);box.addView(Ui.label(this,"BASE URL"));EditText url=Ui.input(this,"https://api.openai.com/v1");url.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);box.addView(url);box.addView(Ui.label(this,"API-КЛЮЧ"));EditText key=Ui.input(this,"Ключ доступа");key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);box.addView(key);box.addView(Ui.label(this,"МОДЕЛЬ"));EditText model=Ui.input(this,"gpt-4o-mini");box.addView(model);if(old!=null){name.setText(old.optString("name"));url.setText(old.optString("baseUrl"));key.setText(old.optString("apiKey"));model.setText(old.optString("model"));}
        LinearLayout actions=Ui.row(this);actions.setGravity(Gravity.END);LinearLayout.LayoutParams ap=Ui.lp(Ui.MATCH,Ui.WRAP,0);ap.topMargin=Ui.dp(this,16);box.addView(actions,ap);Button cancel=Ui.button(this,"Закрыть",false),save=Ui.button(this,"Сохранить",true);actions.addView(cancel);actions.addView(Ui.gap(this,8));actions.addView(save);ScrollView sc=new ScrollView(this);sc.addView(box);Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);d.setContentView(sc);d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.show();int w=Math.min((int)(getResources().getDisplayMetrics().widthPixels*.7f),Ui.dp(this,560));d.getWindow().setLayout(w,WindowManager.LayoutParams.WRAP_CONTENT);d.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);cancel.setOnClickListener(v->d.dismiss());save.setOnClickListener(v->{if(url.getText().toString().trim().isEmpty()||model.getText().toString().trim().isEmpty()){toast("Нужны Base URL и модель.");return;}try{JSONObject p=new JSONObject();String n=name.getText().toString().trim();p.put("name",n.isEmpty()?"ИИ":n);p.put("baseUrl",url.getText().toString().trim());p.put("apiKey",key.getText().toString().trim());p.put("model",model.getText().toString().trim());JSONArray a=providers();if(addNew||a.length()==0){a.put(p);project.optJSONObject("ai").put("active",a.length()-1);}else{int active=project.optJSONObject("ai").optInt("active",0);if(active<0||active>=a.length())active=0;a.put(active,p);project.optJSONObject("ai").put("active",active);}saveProject();updateProviderLabel();d.dismiss();addMessage("Провайдер сохранён. Можно отправлять задачу.",false);log("Настройки ИИ сохранены в Nscript.project",Ui.GREEN);}catch(Exception e){toast(e.getMessage());}});}
    private void sendPrompt(){if(busy)return;String text=prompt.getText().toString().trim();if(text.isEmpty())return;if(provider()==null){providerDialog(true);return;}prompt.setText("");addMessage(text,true);ask(text,0);}
    private void ask(String text,int fixAttempt){
        JSONObject p=provider();
        if(p==null){addMessage("Подключи провайдера сначала.",false);return;}
        final JSONArray messages=new JSONArray();
        try{
            history.add(message("user",text));
            while(history.size()>14)history.remove(0);
            messages.put(message("system",systemPrompt()));
            for(JSONObject m:history)messages.put(m);
        }catch(Exception e){addMessage("Не удалось собрать запрос: "+e.getMessage(),false);return;}
        busy=true;updateProviderLabel();
        TextView waiting=addMessage(fixAttempt==0?"ИИ работает…":"ИИ исправляет ошибку…",false);
        new Thread(()->{
            try{
                String answer=AiClient.complete(p,messages);
                ui.post(()->{if(isFinishing())return;chatMessages.removeView(waiting);busy=false;updateProviderLabel();handle(answer,fixAttempt);});
            }catch(Exception e){
                final String error=e.getMessage()==null?e.toString():e.getMessage();
                ui.post(()->{if(isFinishing())return;chatMessages.removeView(waiting);busy=false;updateProviderLabel();addMessage("Ошибка API: "+error,false);log("ИИ: "+error,0xFFFFC857);});
            }
        }).start();
    }
    private String systemPrompt(){String scene="";try{scene=ProjectStore.read(sceneFile);}catch(Exception ignored){}return "You are the built-in Nova engine coding assistant. User may write Russian. Reply only as one JSON object, no markdown: {\"say\":\"short Russian note\",\"commands\":[...]}. Commands supported: {\"op\":\"spawn\",\"type\":\"cube|sphere|plane|cylinder|empty|light|camera\",\"name\":\"...\",\"pos\":[x,y,z],\"color\":[r,g,b],\"scale\":[x,y,z]}; {\"op\":\"set\",\"name\":\"exact existing name\",\"pos\":[...],\"color\":[...],\"scale\":[...],\"newName\":\"...\"}; {\"op\":\"delete\",\"name\":\"...\"}; {\"op\":\"script\",\"file\":\"Player.ns\",\"code\":\"full source\"}. Use valid JSON escaping. NovaScript execution supports class/file match, fields, OnStart/OnUpdate, if/else, while, for, foreach, break/continue, numeric and string values, basic expressions, vec3, Log, Time.Delta, Math, Scene.Find, Scene.Spawn, Terrain.Create/Generate/SetTexture, Vehicle.Create/Configure/Control, Player.Create, Camera.SetPosition, Tree.Create and Interaction.Chop. Vehicle physics is a simple arcade controller with acceleration, brake, steering, drag and ground clamp. Terrain.Generate stores and renders a procedural heightmap; SetTexture stores procedural material colors. The ▶ button runs it with hot reload and line-number errors. Do not promise photorealistic models, full rigid-body physics, audio or full C# syntax: generators create editable scene primitives until imported art/assets are supplied. Scene format currently: "+scene+" Project type: "+project.optString("template","3d");}
    private JSONObject message(String role,String content)throws Exception{JSONObject m=new JSONObject();m.put("role",role);m.put("content",content);return m;}
    private void handle(String reply,int attempt){try{history.add(message("assistant",reply));}catch(Exception ignored){}JSONObject root=extract(reply);if(root==null){addMessage(reply,false);return;}String say=root.optString("say","");if(!say.isEmpty())addMessage(say,false);JSONArray cmds=root.optJSONArray("commands");if(cmds==null)return;ArrayList<String> errors=new ArrayList<>();int applied=0;for(int i=0;i<cmds.length();i++){JSONObject c=cmds.optJSONObject(i);try{if(c==null)throw new Exception("команда должна быть JSON-объектом");apply(c);applied++;}catch(Exception e){errors.add("Команда "+(i+1)+": "+e.getMessage());}}
        if(applied>0){try{sceneView.reload();}catch(Exception ignored){}refreshFiles();log("ИИ применил команд: "+applied,Ui.GREEN);}if(!errors.isEmpty()){for(String e:errors)log(e,0xFFFF7C86);if(attempt<1){StringBuilder fix=new StringBuilder("Your previous command JSON failed. Fix only these errors, return valid JSON commands only: ");for(String e:errors)fix.append(e).append("; ");ask(fix.toString(),attempt+1);}else addMessage("Часть команд не применена. Ошибки есть в консоли.",false);}}
    private void apply(JSONObject c)throws Exception{String op=c.optString("op","");if("script".equals(op)){String file=c.getString("file").trim();if(!file.endsWith(".ns"))file+=".ns";if(file.contains("/")||file.contains("\\")||file.contains(".."))throw new Exception("для файла скрипта укажи только имя, например Player.ns");String code=c.getString("code");ProjectStore.write(new File(new File(dir,"scripts"),file),code);log("Скрипт записан: scripts/"+file,Ui.GREEN);return;}
        JSONObject scene=new JSONObject(ProjectStore.read(sceneFile));JSONArray a=scene.optJSONArray("objects");if(a==null){a=new JSONArray();scene.put("objects",a);}if("spawn".equals(op)){String type=c.optString("type","cube");if(!Arrays.asList("cube","sphere","plane","cylinder","empty","light","camera").contains(type))throw new Exception("неподдерживаемый тип: "+type);JSONObject o=new JSONObject();o.put("name",unique(a,c.optString("name",type)));o.put("type",type);o.put("visible",true);o.put("position",vec(c,"pos",new double[]{0,0,0}));o.put("rotation",new JSONArray(Arrays.asList(0,0,0)));o.put("scale",vec(c,"scale",new double[]{1,1,1}));o.put("color",vec(c,"color",new double[]{.55,.36,.96}));a.put(o);log("Создан объект "+o.optString("name"),Ui.GREEN);}
        else if("set".equals(op)||"delete".equals(op)){String name=c.optString("name","");int index=find(a,name);if(index<0)throw new Exception("объект «"+name+"» не найден");if("delete".equals(op)){a.remove(index);log("Удалён объект "+name,0xFFFFC857);}else{JSONObject o=a.getJSONObject(index);if(c.has("pos"))o.put("position",vec(c,"pos",null));if(c.has("scale"))o.put("scale",vec(c,"scale",null));if(c.has("color"))o.put("color",vec(c,"color",null));if(c.has("newName"))o.put("name",unique(a,c.getString("newName"),index));}}
        else throw new Exception("неизвестная операция "+op);ProjectStore.write(sceneFile,scene.toString(2));}
    private JSONArray vec(JSONObject c,String key,double[] defaults)throws Exception{JSONArray arr=c.optJSONArray(key);if(arr==null){if(defaults==null)throw new Exception(key+" должен быть [x,y,z]");arr=new JSONArray();for(double x:defaults)arr.put(x);}if(arr.length()<3)throw new Exception(key+" должен содержать три числа");for(int i=0;i<3;i++)if(!Double.isFinite(arr.optDouble(i,Double.NaN)))throw new Exception("нечисловое значение в "+key);return arr;}
    private int find(JSONArray a,String name)throws Exception{for(int i=0;i<a.length();i++)if(name.equals(a.getJSONObject(i).optString("name")))return i;return -1;}
    private String unique(JSONArray a,String base)throws Exception{return unique(a,base,-1);}private String unique(JSONArray a,String base,int except)throws Exception{String n=base.trim().isEmpty()?"Object":base.trim(),baseName=n;int k=2;while(true){boolean exists=false;for(int i=0;i<a.length();i++)if(i!=except&&n.equals(a.getJSONObject(i).optString("name"))){exists=true;break;}if(!exists)return n;n=baseName+" "+k++;}}
    private JSONObject extract(String s){if(s==null)return null;int a=s.indexOf('{'),b=s.lastIndexOf('}');if(a<0||b<=a)return null;try{return new JSONObject(s.substring(a,b+1));}catch(Exception e){return null;}}
    private TextView addMessage(String text,boolean user){TextView t=Ui.text(this,text,13,Ui.TEXT,false);t.setTextIsSelectable(true);t.setPadding(Ui.dp(this,10),Ui.dp(this,8),Ui.dp(this,10),Ui.dp(this,8));t.setBackground(Ui.shape(this,user?0xFF392D55:Ui.RAISED,10,0));LinearLayout.LayoutParams p=Ui.lp(Ui.MATCH,Ui.WRAP,0);p.bottomMargin=Ui.dp(this,6);chatMessages.addView(t,p);chatScroll.post(()->chatScroll.fullScroll(View.FOCUS_DOWN));return t;}
    private void log(String text,int color){TextView t=Ui.text(this,new SimpleDateFormat("HH:mm:ss",Locale.US).format(new Date())+"  "+text,11,color,false);t.setTypeface(android.graphics.Typeface.MONOSPACE);log.addView(t);while(log.getChildCount()>200)log.removeViewAt(0);logScroll.post(()->logScroll.fullScroll(View.FOCUS_DOWN));}
    private void refreshFiles(){if(files==null)return;files.removeAllViews();addFiles(dir,0);}
    private void addFiles(File folder,int depth){File[] a=folder.listFiles();if(a==null)return;Arrays.sort(a,(x,y)->x.isDirectory()!=y.isDirectory()?(x.isDirectory()?-1:1):x.getName().compareToIgnoreCase(y.getName()));for(File f:a){if(f.getName().startsWith("."))continue;if(!f.isDirectory()&&!isOpenableText(f))continue;TextView t=Ui.text(this,(f.isDirectory()?"▸ ":"· ")+f.getName(),12,f.isDirectory()?Ui.MUTED:Ui.TEXT,f.isDirectory());t.setSingleLine(true);t.setEllipsize(TextUtils.TruncateAt.MIDDLE);t.setPadding(Ui.dp(this,depth*9),Ui.dp(this,5),0,Ui.dp(this,5));files.addView(t);if(f.isDirectory())addFiles(f,depth+1);else t.setOnClickListener(v->openText(f));}}
    private void openText(File f){if(f.length()>250000){toast("Файл слишком большой для встроенного просмотра.");return;}try{String code=ProjectStore.read(f);EditText editor=new EditText(this);editor.setText(code);editor.setTextColor(Ui.TEXT);editor.setTextSize(12);editor.setTypeface(android.graphics.Typeface.MONOSPACE);editor.setGravity(Gravity.TOP|Gravity.LEFT);editor.setBackground(Ui.shape(this,Ui.BG,8,Ui.EDGE));LinearLayout box=Ui.col(this);box.setPadding(Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14));box.setBackground(Ui.shape(this,Ui.PANEL,16,Ui.EDGE));box.addView(Ui.text(this,f.getName(),15,Ui.TEXT,true));box.addView(editor,new LinearLayout.LayoutParams(Ui.MATCH,0,1));Button save=Ui.button(this,"Сохранить файл",true);LinearLayout.LayoutParams sp=Ui.lp(Ui.MATCH,Ui.WRAP,0);sp.topMargin=Ui.dp(this,8);box.addView(save,sp);ScrollView scroll=new ScrollView(this);scroll.addView(box);Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);d.setContentView(scroll);d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.show();d.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.85f),(int)(getResources().getDisplayMetrics().heightPixels*.82f));save.setOnClickListener(v->{try{ProjectStore.write(f,editor.getText().toString());d.dismiss();refreshFiles();log("Сохранён файл "+f.getName(),Ui.GREEN);if(f.equals(sceneFile))sceneView.reload();}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){toast("Не удалось открыть: "+e.getMessage());}}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
